import Vue from 'vue'
import { Button,Dropdown,Menu,Popconfirm, Row,Form, Col,Table,Carousel,Modal,Select,DatePicker,Input,Steps,
	Card,Icon,Breadcrumb,Switch,Radio,Checkbox,ConfigProvider,TimePicker, FormModel} from 'ant-design-vue';
Vue.use(Button)
Vue.use(Dropdown)
Vue.use(Menu)
Vue.use(Popconfirm)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(Carousel)
Vue.use(Modal)
Vue.use(Select)
Vue.use(DatePicker)
Vue.use(Input)
Vue.use(Steps)
Vue.use(Form)
Vue.use(Card)
Vue.use(Icon)
Vue.use(Breadcrumb)
Vue.use(Switch)
Vue.use(Radio)
Vue.use(Checkbox)
Vue.use(ConfigProvider)
Vue.use(TimePicker)
Vue.use(FormModel)
